#!/bin/bash
# 
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 and
# only version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

export CFLAGS='-m32 -Wno-unused'
export LDFLAGS=-m32
./configure  --enable-mainainer-mode --target=flexrisc-elf --prefix=/usr/local/opt/zoran/flexrisc/flexrisc-elf --disable-doc-build --disable-nls

